# Linear Algebra
This notebook is focusing in the linear algebra series from the website [Linear Algebra for Programmers](https://www.linearalgebraforprogrammers.com) that is focused on the computational aspect of linear algebra, but with a twist, using numpy.


In [1]:
import numpy as np
from matplotlib import pyplot as plt
import seaborn as sns
import scipy as sp

## 0) A simple reminder of how to do simple Matrix Multiplication

[Link](https://www.linearalgebraforprogrammers.com/la/0_intro)

In [2]:
def vector_matrix_prod(matrix: np.array, vect:np.array):
    #final_v = []
    #for row_vec in matrix:
    #    final_v.append([row_vec*vi for vi in vector])
        
    #return np.array(final_v)
    return vect @ matrix
    
def matrix_prod(left_matrix, right_matrix):
    return [
        vector_matrix_prod(left_matrix, column_vector)
        for column_vector in right_matrix
    ]

m1 = np.arange(1,10).reshape(3,3)
m2 = m1[::-1][::-1]

matrix_prod(m1,m2), m1 @ m2

([array([30, 36, 42]), array([66, 81, 96]), array([102, 126, 150])],
 array([[ 30,  36,  42],
        [ 66,  81,  96],
        [102, 126, 150]]))

## 1) Weighted sums

They can be used to model different stuff, like array indexing, probability, rotation, polynomials, and matrix-vector multiplication.

[Link](https://www.linearalgebraforprogrammers.com/la/1_weighted_means)

In [3]:
def scale_func(values:np.array,weights:np.array):
    return values * weights

def add_func(results:np.array):
    return np.sum(results)

def weighted_sums(values:np.array, weights:np.array, *, scale_function=scale_func, add_function=add_func):
    return add_function(scale_function(values,weights))


v = np.array([2,2,2,2])
u = np.array([3,3,3,3])

weighted_sums(u,v)

np.int64(24)

In [4]:
# Tropical Weighted sum https://en.wikipedia.org/wiki/Tropical_geometry
def tropical_scale(values:np.array,weights:np.array):
    return values + weights

def tropical_add(results:np.array):
    return np.max(results)

weighted_sums(u,v,scale_function=tropical_scale, add_function=tropical_add)

np.int64(5)

In [5]:
# Multi dimensional weighted sums

def scale_arr(arrays:np.array, weights:np.array):
    return np.array([array*weights for array in arrays])

def add_arr(arrays:np.array):
    result = np.zeros(arrays[0].size)
    for arr in arrays:
        result += arr
    return result
        
um = np.full((4,4), 3)

weighted_sums(um,v,scale_function=scale_arr, add_function=add_arr)

array([24., 24., 24., 24.])

## 2 & 3) Vectors, and Matrixes as functions



[Link](https://www.linearalgebraforprogrammers.com/la/2_spacewalk)

In [6]:
# Euclidian distance

def distance(x:np.array, y:np.array):
    return np.linalg.norm(x-y)

distance(u,v)

np.float64(2.0)

In [7]:
m = np.array([[0.5,-0.5],[-0.8,-1]])

np.array([0,2]) @ m

array([-1.6, -2. ])

## 4) Rank and reversibility

Ranks and linear independent components are useful to determine if a matrix is inversible.

[Link](https://www.linearalgebraforprogrammers.com/la/4_rank_and_reversibility)

In [9]:
def equivallent_vec(v1:np.array, v2:np.array):
    return len(np.unique(v1/v2)) == 1

equivallent_vec(u,v)
temp = v.copy()
temp[0] = 10
equivallent_vec(u,temp)

False

In [25]:
rank1 = np.linalg.matrix_rank(um)
rank2 = np.linalg.matrix_rank(np.eye(3))
rank3 = np.linalg.matrix_rank(np.random.random((3,4)))

rank1, rank2, rank3

(np.int64(1), np.int64(3), np.int64(3))

## Barycentric

Useful to find if a point is inside a polygon


[Link](https://www.linearalgebraforprogrammers.com/la/5_barycentric_coordinates)

In [34]:


def is_point_in_triangle(vertices:np.array,point:np.array):
    # centralize one vector into (0,0)
    # compute the inverse matrix of the centrilized vertices (except the origin)
    # validate the weights
    centralizer = vertices[0]
    vertices = vertices - centralizer
    point = point - centralizer

    inverse = np.linalg.inv(vertices[1:])
    weights = point @ inverse
    return np.all(weights > 0) and np.sum(weights) <= 1

is_point_in_triangle(np.array([[3,0],[2,3],[-4,-2]]), np.array([10,10]))    

np.False_